import Navbar from '@components/Navbar/Navbar'
import '@styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}){
  return (
    <html lang='en'>
      <body>
        <div className='main'>
          <div className='gradient'/>
        </div>
        <main className='app'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
